export const CustomTheme = {
  colors: {
    accent: 'inherit',
    base: 'inherit',
    clickable: 'inherit',
    disabled: 'inherit',
    error: 'inherit',
    errorSurface: 'inherit',
    hover: 'inherit',
    surface1: 'inherit',
    surface2: 'inherit',
    surface3: 'inherit',
    warning: 'inherit',
    warningSurface: 'inherit',
  },
  syntax: {
    plain: 'inherit',
    comment: 'inherit',
    keyword: 'inherit',
    tag: 'inherit',
    punctuation: 'inherit',
    definition: 'inherit',
    property: 'inherit',
    static: 'inherit',
    string: 'inherit',
  },
}
