name: Lint GitHub Actions Workflows
on:
  push:
    branches: [main]
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: 'Check workflow files'
        uses: docker://rhysd/actionlint:1.6.23
