name: Canary Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  release-canary:
    uses: hashicorp/web-platform-packages/.github/workflows/release.yml@e173f9719eb796f0a84268dc0f837a0b8943306a
    secrets:
      CHANGESETS_PAT: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
