name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: hashicorp/web-platform-packages/.github/workflows/release.yml@a66d88eda2cb3299c1817aec66052357ef41343d
    secrets:
      CHANGESETS_PAT: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
