name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: hashicorp/web-platform-packages/.github/workflows/release.yml@f5097485701cd34541d66527404256e2036b6338
    secrets:
      PUBLISH_GITHUB_TOKEN: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
