name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: hashicorp/web-platform-packages/.github/workflows/release.yml@22eea7cc2cd47088a9bed590012f85951efc1a9d
    secrets:
      CHANGESETS_PAT: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
