name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: hashicorp/web-platform-packages/.github/workflows/release.yml@d9a428d5ce15668d5792da482b500a97b52e1355
    secrets:
      PUBLISH_GITHUB_TOKEN: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
